[package]
name = "rust-bevy-baios"
version = "0.1.0"
edition = "2021"

#https://doc.rust-lang.org/reference/linkage.html
[lib]
crate-type = ["rlib", "staticlib", "cdylib"]

[dependencies]
# libc = "0.2.152"
jni = "0.21.1"